title: A blog
subtitle: null
description: 又是痛苦的一天呢～
keywords: null
author: Kyra
language: en
timezone: Asia/Hong_Kong
url: 'https://kyrayang.github.io/'
root: /
permalink: ':year/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: Project/CS106A/**/*
new_post_name: ':month:day:title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
index_generator:
  path: ''
  per_page: 5
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
updated_option: true
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
plugins:
  - hexo-renderer-markdown-it
markdown:
  preset: default
  render:
    html: true
    xhtmlOut: false
    langPrefix: language-
    breaks: true
    linkify: true
    typographer: true
    quotes: “”‘’
  enable_rules: null
  disable_rules: null
  plugins:
    - markdown-it-footnote
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false
    permalinkClass: header-anchor
    permalinkSide: left
    permalinkSymbol: ¶
    case: 0
    separator: '-'
theme: next
deploy:
  type: git
  branch: master
  repo: >-
    https://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@github.com/KyraYang/kyrayang.github.io
  message: 'Site updated {{ now(''YYYY-MM-DD HH:mm:ss'') }}'
favicon:
  small: /source/images/favicon.ico
